const DATABASE_CREDENTIALS = {
    // Credenziali predefinite del docente
    users: [
        { username: "fattori", password: "prof", role: "docente", nome: "Prof. Nicholas Fattori" },
        { username: "gazzetto", password: "daniel2026", role: "studente", nome: "Studente Daniel Gazzetto" },
        { username: "boulmane", password: "mohamedali2026", role: "studente", nome: "Studente Mohamed Ali Boulmane" },
        { username: "jait", password: "othmane2026", role: "studente", nome: "Studente Othmane Jait" },
        { username: "negretto", password: "alessio2026", role: "studente", nome: "Studente Alessio Negretto" },
        { username: "dalcero", password: "thomas2026", role: "studente", nome: "Studente Thomas Dal Cero" },
        { username: "confente", password: "anvedi2026", role: "studente", nome: "Studente Thomas Confente" },
        { username: "kumar", password: "divyansh2026", role: "studente", nome: "Studente Divyansh Kumar" },
        { username: "cavazza", password: "leandro2026", role: "studente", nome: "Studente Leandro Cavazza" },
        { username: "santillo", password: "paride2026", role: "studente", nome: "Studente Paride Santillo" },
        { username: "bruzzo", password: "gabriele2026", role: "studente", nome: "Studente Gabriele Bruzzo" },
        { username: "paticchia", password: "marco2026", role: "studente", nome: "Studente Marco Paticchia" },
        { username: "cukovic", password: "sergej2026", role: "studente", nome: "Studente Sergej Cukovic" },
        { username: "rachidi", password: "rida2026", role: "studente", nome: "Studente Rida Rachidi" },
        { username: "facchin", password: "devis2026", role: "studente", nome: "Studente Devis Facchin" },
        { username: "lamaangad", password: "sami2026", role: "studente", nome: "Studente Sami Lamaangad" },
        { username: "bertolaso", password: "lorenzo2026", role: "studente", nome: "Studente Lorenzo Bertolaso" },
        { username: "marini", password: "mattia2026", role: "studente", nome: "Studente Mattia Marini" },
        { username: "azzi", password: "rayan2026", role: "studente", nome: "Studente Rayan Azzi" },
        { username: "belllin", password: "enrico2026", role: "studente", nome: "Studente Enrico Bellin" },
        { username: "carlan", password: "lorenzo2026", role: "studente", nome: "Studente Lorenzo Carlan" },
        { username: "damini", password: "mattia2026", role: "studente", nome: "Studente Mattia Damini" },
        { username: "garbouch", password: "yassin2026", role: "studente", nome: "Studente Yassin Garbouch" },
        { username: "kebe", password: "mamadoubamba2026", role: "studente", nome: "Studente Mamadou Bamba Kebe" },
        { username: "kusi", password: "markoduro2026", role: "studente", nome: "Studente Mark Oduro Kusi" },
        { username: "singh", password: "anmol2026", role: "studente", nome: "Studente Anmol Singh" },
        { username: "stevic", password: "rayan2026", role: "studente", nome: "Studente Ryan Stevic" },
        { username: "saraci", password: "francesco2026", role: "studente", nome: "Studente Francesco Saraci" },
        { username: "billo", password: "marco2026", role: "studente", nome: "Studente Marco Billo" },
        { username: "bujor", password: "denisionut2026", role: "studente", nome: "Studente Denis Ionut Bujor" },
        { username: "chakir", password: "mohammed2026", role: "studente", nome: "Studente Mohammed Chakir" },
        { username: "chiovetto", password: "cristian2026", role: "studente", nome: "Studente Cristian Chiovetto" },
        { username: "colognese", password: "gioele2026", role: "studente", nome: "Studente Gioele Colognese" },
        { username: "dibattista", password: "hilary2026", role: "studente", nome: "Studente Hilary Di Battista" },
        { username: "elhasnaoui", password: "ayman2026", role: "studente", nome: "Studente Ayman El Hasnaoui" },
        { username: "gaignard", password: "andrea2026", role: "studente", nome: "Studente Andrea Gaignard" },
        { username: "grandi", password: "mirco2026", role: "studente", nome: "Studente Mirco Grandi" },
        { username: "grisi", password: "francescogiovanni2026", role: "studente", nome: "Studente Francesco Giovanni Grisi" },
        { username: "lal", password: "mohit2026", role: "studente", nome: "Studente Mohit Lal" },
        { username: "longo", password: "manuel2026", role: "studente", nome: "Studente Manuel Longo" },
        { username: "nibaoui", password: "ahmed2026", role: "studente", nome: "Studente Ahmed Nibaoui" },
        { username: "paluka", password: "klevis2026", role: "studente", nome: "Studente Klevis Paluka" },
        { username: "penzo", password: "timothy2026", role: "studente", nome: "Studente Timothy Penzo" },
        { username: "sammartino", password: "emanuele2026", role: "studente", nome: "Studente Emanuele Sammartino" },
        { username: "scalmazzi", password: "nicolas2026", role: "studente", nome: "Studente Nicolas Scalmazzi" },
        { username: "scarparo", password: "alberto2026", role: "studente", nome: "Studente Alberto Scarparo" },
        { username: "sestito", password: "francescojunior2026", role: "studente", nome: "Studente Francesco Junior Sestito" },
        { username: "singh", password: "ekamjit2026", role: "studente", nome: "Studente Ekamjit Singh" },
        { username: "tufa", password: "alex2026", role: "studente", nome: "Studente Alex Tufa" },
        { username: "xhani", password: "aleksander2026", role: "studente", nome: "Studente Aleksander Khani" },
        { username: "zorzi", password: "michele2026", role: "studente", nome: "Studente Michele Zorzi" },
        { username: "abbamonte", password: "francesco2026", role: "studente", nome: "Studente Francesco Abbamonte" },
        { username: "ajdini", password: "egli2026", role: "studente", nome: "Studente Egli Ajdini" },
        { username: "aldighieri", password: "michele", role: "studente", nome: "Studente Michele Aldighieri" },
        { username: "abdelbasset", password: "arinate2026", role: "studente", nome: "Studente Arinate Abdelbasset" },
        { username: "axinia", password: "marcocostantin2026", role: "studente", nome: "Studente Marco Costantin Axinia" },
        { username: "barbu", password: "stefanofrancesco2026", role: "studente", nome: "Studente Stefano Francesco Barbu" },
        { username: "belba", password: "gioele2026", role: "studente", nome: "Studente Gioele Belba" },
        { username: "bissolo", password: "andrea2026", role: "studente", nome: "Studente Andrea Bissolo" },
        { username: "bongiovanni", password: "nicola2026", role: "studente", nome: "Studente Nicola Bongiovanni" },
        { username: "campaci", password: "gabriele2026", role: "studente", nome: "Studente Gabriele Campaci" },
        { username: "chahi", password: "omar2026", role: "studente", nome: "Studente Omar Chahi" },
        { username: "debenedictis", password: "alberto2026", role: "studente", nome: "Studente Alberto De Benedictis" },
        { username: "degregori", password: "thomas2026", role: "studente", nome: "Studente Thomas De Gregori" },
        { username: "deluca", password: "giovanni2026", role: "studente", nome: "Studente Giovanni De Luca" },
        { username: "eshun", password: "nathanael2026", role: "studente", nome: "Studente Nathanael Eshun" },
        { username: "gianesini", password: "nicolò2026", role: "studente", nome: "Studente Nicolò Gianesini" },
        { username: "olivetto", password: "filippo2026", role: "studente", nome: "Studente Filippo Olivetto" },
        { username: "pecorella", password: "eros2026", role: "studente", nome: "Studente " },
        { username: "percali", password: "edoardo2026", role: "studente", nome: "Studente " },
        { username: "posenato", password: "matteo2026", role: "studente", nome: "Studente " },
        { username: "sacko", password: "daouda2026", role: "studente", nome: "Studente " },
        { username: "sadeq", password: "aymen", role: "studente", nome: "Studente Aymen Sadeq" },
        { username: "singh", password: "jasraj", role: "studente", nome: "Studente Jasraj Singh" },
        { username: "singh", password: "kartik", role: "studente", nome: "Studente Kartik Singh" },
        { username: "singh", password: "sarabjit", role: "studente", nome: "Studente Sarabjit Singh" },
        { username: "trentin", password: "emmanuela2026", role: "docente", nome: "Prof.ssa Trentin Emmanuela" },
        { username: "dudau", password: "mirela2026", role: "docente", nome: "Prof.ssa Dudau Mirela" },
        { username: "volpe", password: "salvatore2026", role: "docente", nome: "Prof.ssa Volpe Salvatore" },
        { username: "lucente", password: "fabio2026", role: "docente", nome: "Prof. Lucente Fabio" }
    ],
    maxAttempts: 3 // Numero massimo di tentativi consentiti
};

// Esporta la configurazione per gli altri script
window.DB_CONFIG = DATABASE_CREDENTIALS;
